create table if not exists public.shifts (
  id integer generated by default as identity primary key,
  name varchar(120) not null,
  start_time varchar(5) not null,
  end_time varchar(5) not null,
  late_tolerance_minutes integer not null default 10,
  early_leave_tolerance_minutes integer not null default 10,
  checkin_open_minutes_before integer not null default 30,
  checkout_open_minutes_before integer not null default 30,
  is_overnight boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.employees (
  id integer generated by default as identity primary key,
  employee_code varchar(50) unique not null,
  full_name varchar(200) not null,
  email varchar(255) unique not null,
  phone varchar(40) not null default '',
  department varchar(100) not null,
  position varchar(120) not null default '',
  status varchar(40) not null default 'active',
  default_shift_id integer references public.shifts(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.users (
  id integer generated by default as identity primary key,
  username varchar(80) unique not null,
  email varchar(255) unique not null,
  password_hash varchar(255) not null,
  role varchar(40) not null default 'manager',
  is_active boolean not null default true,
  employee_id integer references public.employees(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.face_samples (
  id integer generated by default as identity primary key,
  employee_id integer not null references public.employees(id),
  cropped_face_url text not null,
  quality_score double precision not null,
  model_name varchar(120) not null,
  embedding_version varchar(80) not null,
  embedding text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.attendance_logs (
  id integer generated by default as identity primary key,
  employee_id integer not null references public.employees(id),
  device_id varchar(120) not null,
  action_type varchar(40) not null,
  event_time timestamptz not null,
  score double precision not null,
  threshold double precision not null,
  is_live boolean not null default true,
  snapshot_url text,
  status varchar(40) not null,
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.system_configs (
  key varchar(120) primary key,
  value text not null,
  description text not null default '',
  updated_at timestamptz not null default now()
);

create index if not exists ix_employees_employee_code on public.employees(employee_code);
create index if not exists ix_employees_email on public.employees(email);
create index if not exists ix_users_username on public.users(username);
create index if not exists ix_users_email on public.users(email);
create index if not exists ix_face_samples_employee_id on public.face_samples(employee_id);
create index if not exists ix_attendance_logs_employee_id on public.attendance_logs(employee_id);
create index if not exists ix_attendance_logs_event_time on public.attendance_logs(event_time);
create index if not exists ix_attendance_logs_status on public.attendance_logs(status);
create index if not exists ix_attendance_logs_device_id on public.attendance_logs(device_id);

grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant usage, select, update on all sequences in schema public to anon, authenticated;

