create table if not exists public.shifts (
  id integer generated by default as identity primary key,
  name varchar(120) not null,
  start_time varchar(5) not null,
  end_time varchar(5) not null,
  late_tolerance_minutes integer not null default 10,
  early_leave_tolerance_minutes integer not null default 10,
  checkin_open_minutes_before integer not null default 30,
  checkout_open_minutes_before integer not null default 30,
  is_overnight boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.employees (
  id integer generated by default as identity primary key,
  employee_code varchar(50) unique not null,
  full_name varchar(200) not null,
  email varchar(255) unique not null,
  phone varchar(40) not null default '',
  department varchar(100) not null,
  position varchar(120) not null default '',
  status varchar(40) not null default 'active',
  default_shift_id integer references public.shifts(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.users (
  id integer generated by default as identity primary key,
  username varchar(80) unique not null,
  email varchar(255) unique not null,
  password_hash varchar(255) not null,
  role varchar(40) not null default 'manager',
  is_active boolean not null default true,
  employee_id integer references public.employees(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.face_samples (
  id integer generated by default as identity primary key,
  employee_id integer not null references public.employees(id),
  cropped_face_url text not null,
  quality_score double precision not null,
  model_name varchar(120) not null,
  embedding_version varchar(80) not null,
  embedding text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.attendance_logs (
  id integer generated by default as identity primary key,
  employee_id integer not null references public.employees(id),
  device_id varchar(120) not null,
  action_type varchar(40) not null,
  event_time timestamptz not null,
  score double precision not null,
  threshold double precision not null,
  is_live boolean not null default true,
  snapshot_url text,
  status varchar(40) not null,
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.anomaly_flags (
  id integer generated by default as identity primary key,
  attendance_log_id integer not null references public.attendance_logs(id),
  employee_id integer not null references public.employees(id),
  rule_key varchar(120) not null,
  severity varchar(40) not null default 'warning',
  title varchar(200) not null,
  description text not null default '',
  status varchar(40) not null default 'open',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewer_user_id integer references public.users(id),
  resolution_note text
);

create table if not exists public.attendance_audit_logs (
  id integer generated by default as identity primary key,
  attendance_log_id integer not null references public.attendance_logs(id),
  actor_user_id integer references public.users(id),
  actor_username varchar(80) not null default 'system',
  action varchar(80) not null,
  before_value text not null default '{}',
  after_value text not null default '{}',
  reason text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.attendance_email_notifications (
  id integer generated by default as identity primary key,
  attendance_log_id integer unique not null references public.attendance_logs(id),
  employee_id integer not null references public.employees(id),
  recipient_email varchar(255) not null,
  status varchar(40) not null default 'sent',
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_attendance_email_notifications (
  id integer generated by default as identity primary key,
  employee_id integer not null references public.employees(id),
  work_date varchar(10) not null,
  recipient_email varchar(255) not null,
  status varchar(40) not null default 'sent',
  summary_status varchar(80) not null default '',
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  constraint uq_daily_attendance_email_employee_date unique (employee_id, work_date)
);

create table if not exists public.leave_calendar (
  id integer generated by default as identity primary key,
  employee_id integer references public.employees(id),
  leave_date varchar(10) not null,
  leave_type varchar(80) not null default 'leave',
  reason text not null default '',
  status varchar(40) not null default 'approved',
  created_by_user_id integer references public.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.system_configs (
  key varchar(120) primary key,
  value text not null,
  description text not null default '',
  updated_at timestamptz not null default now()
);

create index if not exists ix_employees_employee_code on public.employees(employee_code);
create index if not exists ix_employees_email on public.employees(email);
create index if not exists ix_users_username on public.users(username);
create index if not exists ix_users_email on public.users(email);
create index if not exists ix_face_samples_employee_id on public.face_samples(employee_id);
create index if not exists ix_attendance_logs_employee_id on public.attendance_logs(employee_id);
create index if not exists ix_attendance_logs_event_time on public.attendance_logs(event_time);
create index if not exists ix_attendance_logs_status on public.attendance_logs(status);
create index if not exists ix_attendance_logs_device_id on public.attendance_logs(device_id);
create index if not exists ix_anomaly_flags_attendance_log_id on public.anomaly_flags(attendance_log_id);
create index if not exists ix_anomaly_flags_employee_id on public.anomaly_flags(employee_id);
create index if not exists ix_anomaly_flags_rule_key on public.anomaly_flags(rule_key);
create index if not exists ix_anomaly_flags_severity on public.anomaly_flags(severity);
create index if not exists ix_anomaly_flags_status on public.anomaly_flags(status);
create index if not exists ix_attendance_audit_logs_attendance_log_id on public.attendance_audit_logs(attendance_log_id);
create index if not exists ix_attendance_email_notifications_attendance_log_id on public.attendance_email_notifications(attendance_log_id);
create index if not exists ix_attendance_email_notifications_employee_id on public.attendance_email_notifications(employee_id);
create index if not exists ix_attendance_email_notifications_status on public.attendance_email_notifications(status);
create index if not exists ix_daily_attendance_email_notifications_employee_id on public.daily_attendance_email_notifications(employee_id);
create index if not exists ix_daily_attendance_email_notifications_work_date on public.daily_attendance_email_notifications(work_date);
create index if not exists ix_daily_attendance_email_notifications_status on public.daily_attendance_email_notifications(status);
create index if not exists ix_leave_calendar_employee_id on public.leave_calendar(employee_id);
create index if not exists ix_leave_calendar_leave_date on public.leave_calendar(leave_date);
create index if not exists ix_leave_calendar_status on public.leave_calendar(status);

grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant usage, select, update on all sequences in schema public to anon, authenticated;
